# Generated by Django 5.1.7 on 2025-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('created_for', models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('instructors', 'All Instructors'), ('specific_student', 'Specific Student'), ('specific_instructor', 'Specific Instructor'), ('class_students', 'Class Students'), ('class_instructors', 'Class Instructors')], max_length=50)),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
