# Generated by Django 5.1.7 on 2025-03-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
