# Generated by Django 5.1.7 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_for', models.CharField(choices=[('all', 'All'), ('instructor', 'Instructor'), ('student', 'Student')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/images/')),
                ('instructors', models.ManyToManyField(blank=True, to='lms.instructor')),
                ('students', models.ManyToManyField(blank=True, to='lms.student')),
            ],
        ),
    ]
